<div class="page-header clearfix">
    <h2>
        <?= !empty($customer->getId()) ? 'Edit': 'New' ?> Customer
    </h2>
</div>
<form action="" method="post" role="form">
    <div class="form-group">
        <label for="name">
            Name:
        </label>
        <input class="form-control" id="name" name="name" placeholder="Enter Name" type="text" value="<?= $this->customer->getName() ?>">
        </input>
        <?= $this->validationErrors('name') ?>
    </div>
    <div class="form-group">
        <label for="email">
            Email:
        </label>
        <input class="form-control" id="email" name="email" placeholder="Enter Email" type="text" value="<?= $this->customer->getEmail() ?>">
        </input>
        <?= $this->validationErrors('email') ?>
    </div>
    <button class="btn btn-primary" type="submit">
        Save
    </button>
</form>
